//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONECT
    {
        public int id_conect { get; set; }
        public int id_usuario { get; set; }
        public string equipo { get; set; }
        public string ip { get; set; }
        public System.DateTime fechaconect { get; set; }
        public Nullable<System.TimeSpan> horaconect { get; set; }
        public Nullable<System.DateTime> fechadesconect { get; set; }
        public Nullable<System.TimeSpan> horadesconect { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
