//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIALPWD
    {
        public int id_hpwd { get; set; }
        public int id_usuario { get; set; }
        public string oldpwd { get; set; }
        public string newpwd { get; set; }
        public Nullable<System.DateTime> fechacambio { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
