//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_conect
    {
        public int id_conect { get; set; }
        public string login { get; set; }
        public bool conectado { get; set; }
        public string equipo { get; set; }
        public string ip { get; set; }
        public System.DateTime fecha_de_conexion { get; set; }
        public Nullable<System.DateTime> fecha_de_desconexion { get; set; }
    }
}
