//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS_PERFIL
    {
        public int id_movper { get; set; }
        public int id_perfil { get; set; }
        public int id_usuario { get; set; }
        public int id_mov { get; set; }
        public Nullable<int> id_sector { get; set; }
        public string permisoanterio { get; set; }
        public string permisoactual { get; set; }
        public System.DateTime fechamov { get; set; }
        public System.TimeSpan horamov { get; set; }
    
        public virtual TIPO_MOV_PERFIL TIPO_MOV_PERFIL { get; set; }
        public virtual PERFIL PERFIL { get; set; }
        public virtual SECTORES SECTORES { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
