//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_SECTOR
    {
        public int id_perfil { get; set; }
        public int id_sector { get; set; }
        public Nullable<bool> permitido { get; set; }
    
        public virtual PERFIL PERFIL { get; set; }
        public virtual SECTORES SECTORES { get; set; }
    }
}
