//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGUIMIENTO_DOCTOS
    {
        public int Num_Solicitud { get; set; }
        public Nullable<System.DateTime> Repc_Doc { get; set; }
        public Nullable<System.DateTime> Analisis_Mac { get; set; }
        public Nullable<System.DateTime> Formalizada { get; set; }
        public Nullable<System.DateTime> Repc_Originales { get; set; }
        public Nullable<System.DateTime> Aten_Originales { get; set; }
        public string Originales { get; set; }
        public string Nivel_Servicico { get; set; }
        public Nullable<decimal> Deposito_Inicial { get; set; }
        public Nullable<System.DateTime> Desbloqueo_Sistemas { get; set; }
        public Nullable<System.DateTime> Envio_Agencia { get; set; }
        public Nullable<System.DateTime> Concluida { get; set; }
        public Nullable<System.DateTime> Cancelacion { get; set; }
        public int Id_SeguimientoDoc { get; set; }
    
        public virtual SEGUIMIENTO SEGUIMIENTO { get; set; }
    }
}
