//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGUIMIENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEGUIMIENTO()
        {
            this.SEGUIMIENTO_OBSERVACIONES = new HashSet<SEGUIMIENTO_OBSERVACIONES>();
        }
    
        public int Num_Solicitud { get; set; }
        public Nullable<System.DateTime> Fecha_Captura { get; set; }
        public Nullable<int> Id_ConsultorMac { get; set; }
        public Nullable<int> Id_Solicitud { get; set; }
        public Nullable<int> Id_Tramite { get; set; }
        public string ExisteTKT { get; set; }
        public Nullable<int> Puntos { get; set; }
        public string Circuito { get; set; }
        public string Cuenta_Cliente { get; set; }
        public string Sufijo_Kapiti { get; set; }
        public Nullable<byte> Tipo_Persona { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public Nullable<decimal> Deposito_InicialTKT { get; set; }
        public string Numero_Registro { get; set; }
        public string Nombre_Promotor { get; set; }
        public string Banca { get; set; }
        public string Division { get; set; }
        public string Plaza { get; set; }
        public string Sucursal { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEGUIMIENTO_OBSERVACIONES> SEGUIMIENTO_OBSERVACIONES { get; set; }
        public virtual SEGUIMIENTO_DOCTOS SEGUIMIENTO_DOCTOS { get; set; }
        public virtual TIPO_SOLICITUD TIPO_SOLICITUD { get; set; }
        public virtual TIPO_TRAMITE TIPO_TRAMITE { get; set; }
    }
}
