//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.CONECT = new HashSet<CONECT>();
            this.HISTORIALPWD = new HashSet<HISTORIALPWD>();
            this.MOVIMIENTOS_PERFIL = new HashSet<MOVIMIENTOS_PERFIL>();
            this.MOVIMIENTOS_USUARIO = new HashSet<MOVIMIENTOS_USUARIO>();
            this.MOVIMIENTOS_USUARIO1 = new HashSet<MOVIMIENTOS_USUARIO>();
        }
    
        public int id_usuario { get; set; }
        public int id_perfil { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public bool fechaexpira { get; set; }
        public Nullable<System.DateTime> fecha_de_expiracion { get; set; }
        public bool habilitado { get; set; }
        public bool bloqueado { get; set; }
        public System.DateTime fechacreacion { get; set; }
        public bool conectado { get; set; }
        public Nullable<bool> nuevoinicio { get; set; }
        public Nullable<bool> resetpwd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONECT> CONECT { get; set; }
        public virtual CONSULTORES CONSULTORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIALPWD> HISTORIALPWD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTOS_PERFIL> MOVIMIENTOS_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTOS_USUARIO> MOVIMIENTOS_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMIENTOS_USUARIO> MOVIMIENTOS_USUARIO1 { get; set; }
        public virtual PERFIL PERFIL { get; set; }
    }
}
