//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ver_mov_usuario
    {
        public int C_Movimiento { get; set; }
        public string Usuario_que_realizo_el_movimiento { get; set; }
        public string Usuario_modificado { get; set; }
        public string Movimiento { get; set; }
        public string Dato_anterio { get; set; }
        public string Dato_actual { get; set; }
        public Nullable<System.DateTime> Fecha_del_movimiento { get; set; }
        public Nullable<System.TimeSpan> Hora_del_movimiento { get; set; }
    }
}
