//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ver_mov_perfil
    {
        public int C_Movimiento { get; set; }
        public string Usuario { get; set; }
        public string Perfil { get; set; }
        public string Movimiento { get; set; }
        public string Sector { get; set; }
        public string Permiso_anterior { get; set; }
        public string Permiso_actual { get; set; }
        public System.DateTime fecha_del_movimiento { get; set; }
        public string Hora_del_cambio { get; set; }
    }
}
