//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ver_conect2
    {
        public int C_Conexion { get; set; }
        public string Usuario { get; set; }
        public string Equipo { get; set; }
        public string Direccion_IP { get; set; }
        public System.DateTime Fecha_de_conexion { get; set; }
        public string Hora_de_conexion { get; set; }
        public string Fecha_de_desconexion { get; set; }
        public string Hora_de_desconexion { get; set; }
    }
}
