//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ver_mov_solicitudes
    {
        public int Num_Solicitud { get; set; }
        public string Cuenta_Cliente { get; set; }
        public Nullable<System.DateTime> Fecha_Captura { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Descripcion_Status { get; set; }
    }
}
