//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOMAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ver_consultores
    {
        public int Id_ConsultorMac { get; set; }
        public string Iniciales_ConsultorMac { get; set; }
        public string Nom_ConsultorMac { get; set; }
        public string Ap_ConsultorMac { get; set; }
        public string Am_ConsultorMac { get; set; }
    }
}
